# ---------------------------------------------
#           This file is part of
#      _  _   __    _   _    __    __
#     ( \/ ) /__\  ( )_( )  /__\  (  )
#      \  / /(__)\  ) _ (  /(__)\  )(__
#      (__)(__)(__)(_) (_)(__)(__)(____)
#
#     Yet Another HW Abstraction Library
#      Copyright (C) Andreas Terstegge
#      BSD Licensed (see file LICENSE)
#
# ---------------------------------------------

# platform and YAHAL location
PLATFORM  = msp432
YAHAL_DIR = ../../..

# name of final target
TARGET = example_blink_asm.out

# folder for build artifacts
# (same as eclipse build folder)
BUILD_DIR = Debug

# all source folders of our project
SRC_DIRS = .

include $(YAHAL_DIR)/makefiles/common.mk

