//
// This file was generated by file2cpp, a small
// program to convert any binary or text file
// into a C/C++ struct of unsigned characters.
//
//  Source file was: image.bin (size: 22528 bytes)
//

#include <cstdint>

extern const uint8_t image[22528];
